version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://golf-club-db.c1qmug2cah4m.ca-central-1.rds.amazonaws.com:5432/golfclub
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=GolfClub2026!
    restart: unless-stopped
