# Database Configuration
spring.datasource.url=jdbc:postgresql://golf-club-db.c1qmug2cah4m.ca-central-1.rds.amazonaws.com:5432/golfclub
spring.datasource.username=postgres
spring.datasource.password=GolfClub2026!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080